### PR TITLE
Fix tests when using MacOS

### PR DESCRIPTION
**Pull request by nocturnalastro**

### CODE REVIEW

**Review by natifridman — APPROVED** [review]
/lgtm
Works on my Mac M3

**Comment by AlinaSecret** [comment]
@nocturnalastro in the end the yaml check is more elegant then i expected :) 
looks good, Thanks!!! 
\lgtm

**Comment by pixelsoccupied** [comment]
/lgtm 
/approve

Looks like it's more generic that just macos specific! Thanks!

**Pull request merged**
