### PR TITLE
Add krew-bump.sh helper script for updating the krew index as part of release

### PR DESCRIPTION
**Pull request by lack**
Signed-off-by: Jim Ramsay <jramsay@redhat.com>

### CODE REVIEW

**Review by natifridman — COMMENTED** [review]
Maybe we can use Krew auto update? https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/

**Comment by lack** [comment]
@natifridman : I looked into that automation, but it only seems to be designed to work with github actions and I'm not sure that jives with the openshift org prow integration :(

**Review by natifridman — APPROVED** [review]
/lgtm

**Pull request merged**
